version: "3.5"

services: 
    main:
        build: 
            context: ./
            dockerfile: ./Dockerfile
            target: dev
        environment: 
            ENVIRONMENT: local
        working_dir: /app
        tty: true
        volumes: 
            - ./:/app
            - /app/node_modules/bcrypt/
        ports: 
            - 3000:3000
            - 9229:9229
        networks: 
            - part-supply-bff-net
        depends_on: 
            - my-sql-db
    
    my-sql-db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'part-supply-db-local'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
        # Where our data will be persisted
        volumes:
            - part-supply-db:/var/lib/mysql
        networks: 
            - part-supply-bff-net
# Names our volume
volumes:
  part-supply-db:
networks:
    part-supply-bff-net:
        driver: bridge
